In [9]:
# Run this cell first!
import otter
grader = otter.Notebook("Homework3.ipynb")

In [10]:
#pip install otter-grader

Defaulting to user installation because normal site-packages is not writeable
  Using cached PyYAML-6.0.2-cp312-cp312-win_amd64.whl.metadata (2.1 kB)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
  Using cached wrapt-1.16.0-cp312-cp312-win_amd64.whl.metadata (6.8 kB)
  Using cached wheel-0.44.0-py3-none-any.whl.metadata (2.3 kB)
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
  Using cached tqdm-4.66.5-py3-none-any.whl.metadata (57 kB)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
  Using cached charset_normalizer-3.3.2-cp312-cp312-win_amd64.whl.metadata (34 kB)
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
  Using cached attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
  Using cached soupsieve-2.6-py3-none-any.whl.metadata (4.6 kB)
Using cached PyYAML-6.0.2-cp312-cp312-win_amd64.whl (156 kB)
Using cached requests-2.32.3-py3

# Data Programming in Python | BAIS:6040
# Homework 3. User-Defined Functions, Exceptions, and Numpy

10 questions, 6 points in total

## Instructions

- Fill in the Python statements needed to complete all the questions below. 
- Program everything inside this notebook. 
- Use only one cell per question. 
- Each code cell must be run with no errors.
- Do not contain any unnecessary code in your answer. (Only the final outcome will be regarded as your answer.)
- If the question requests that you store information in a certain variable, use the specific variables name (case sensitive).
- All problems must be solved in a programmable way.
- When you are done, make sure to save your notebook and then click Restart & Run All before subimission to create a clean version.

## Questions

1\. (0.6 pts) Write a function `get_stats` that takes a list `l` of integers as an argument and returns a tuple of the min, max, and sum of only the positive numbers in `l` for each. You may need a temporary list like `l_tmp` to store only the positive numbers in `l`. Use a for loop to fill in `l_tmp`.

Note: Do not use the <b>print</b> function in this question. The function returns a tuple, not prints it. 

In [10]:
# Your answer here
def get_stats(l):
    l_tmp = [num for num in l if num > 0]
    if not l_tmp:
        return (None, None, 0)
    return (min(l_tmp), max(l_tmp), sum(l_tmp))

In [11]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
get_stats([1, 3, 2])            # Output: (1, 3, 6)

(1, 3, 6)

In [12]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
get_stats([-1, 1, 0, 3, 2])     # Output: (1, 3, 6)

(1, 3, 6)

In [13]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
get_stats([5, 10, 15])     # Output: (5, 15, 30)

(5, 15, 30)

In [14]:
grader.check("Question01")

Question01 results: All test cases passed!

2\. (0.6 pts) Write a function `get_stats2` that works the same as `get_stats` above, but, additionally, it returns the  '*Invalid value!*' string when it finds any non-integer in `l`. Use a for loop to check if each item in `l` is an integer.

Note: Do not use the <b>print</b> function in this question. The function returns either a tuple or a string, not prints it. 

In [15]:
# Your answer here
def get_stats2(l):
    for item in l:
        if not isinstance(item, int):
            return 'Invalid value!'
    l_tmp = [num for num in l if num > 0]
    if not l_tmp:
        return (None, None, 0)
    return (min(l_tmp), max(l_tmp), sum(l_tmp))

In [16]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
get_stats2([-1, 1, 0, 3, 2])     # Output: (1, 3, 6)

(1, 3, 6)

In [17]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
get_stats2([-1, 1, 0.0, 3, 2])   # Output: 'Invalid value!'.

'Invalid value!'

In [18]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
get_stats2([-1, 1, "0", 3, 2])   # Output: 'Invalid value!'.

'Invalid value!'

In [19]:
grader.check("Question02")

Question02 results: All test cases passed!

3\. (0.6 pts) Write a function `truncate` that takes a string `s` and an integer `limit` as arguments and returns the string as it is if the length of the string is equal to or less than `limit`. If the length is greater than `limit`, it only takes the `limit`-length leading substring of `s` (i.e., from the index position 0 to `limit` -1) replacing the rest of `s` with '...' and returns that truncated string. Set the default value for `limit` to 50.

Note: Do not use the <b>print</b> function in this question. The function returns a string, not prints anything. 

In [20]:
# Your answer here
def truncate(s, limit=50):
    if len(s) <= limit:
        return s
    return s[:limit] + '...'

In [21]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
truncate("I'm learning Python data analytics.", 100)

# Output: "I'm learning Python data analytics."

"I'm learning Python data analytics."

In [22]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
truncate("I'm learning Python data analytics.", 10)

# Output: "I'm learni..."

"I'm learni..."

In [23]:
# Test your function here. (Do not make any change to this cell. Just run this cell.)
truncate("I'm learning Python data analytics. Python is a general purpose programming language.")

# Output: "I'm learning Python data analytics. Python is a ge..."

"I'm learning Python data analytics. Python is a ge..."

In [25]:
grader.check("Question03")

Question03 results: All test cases passed!

4\. (0.6 pts) Create a dictionary `kwargs` that sets the argument values of `s` to any string longer than 30 characters and `limit` to 30 and then call the `truncate` function by passing `kwargs`.

In [26]:
# Your answer here 

kwargs = {
    's': "I'm learning Python data analytics",
    'limit': 30
}

# Call the truncate function with the dictionary
truncate(**kwargs)

"I'm learning Python data analy..."

In [27]:
grader.check("Question04")

Question04 results: All test cases passed!

5\. (0.6 pts) To use NumPy, import the NumPy package as np.

In [28]:


# Your answer here
import numpy as np

In [29]:
grader.check("Question05")

Question05 results: All test cases passed!

6\. (0.6 pts) Set the random seed to 0 and then create a 10 x 10 array `x` of random integers between 1 (inclusive) and 100 (inclusive).

In [30]:
# Your answer here 
np.random.seed(0)
x = np.random.randint(1, 101, size=(10, 10))

In [31]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
x

array([[ 45,  48,  65,  68,  68,  10,  84,  22,  37,  88],
       [ 71,  89,  89,  13,  59,  66,  40,  88,  47,  89],
       [ 82,  38,  26,  78,  73,  10,  21,  81,  70,  80],
       [ 48,  65,  83, 100,  89,  50,  30,  20,  20,  15],
       [ 40,  33,  66,  10,  58,  33,  32,  75,  24,  36],
       [ 76,  56,  29,  35,   1,   1,  37,  54,   6,  39],
       [ 18,  80,   5,  43,  59,  32,   2,  66,  42,  58],
       [ 36,  12,  47,  83,  92,   1,  15, 100,  54,  13],
       [ 43,  85,  76,  69,   7,  69,  48,   4,  77,  53],
       [ 79,  16,  21, 100,  59,  24,  80,  14,  86,  49]], dtype=int32)

In [32]:
grader.check("Question06")

Question06 results: All test cases passed!

7\. (0.6 pts) Create a 10 x 10 array `y` of integers from 100 (inclusive) to 1 (inclusive), such that the first row has integers from 100 to 91, the second row from 90 to 81, and so on and so forth. Note that order of values matters. 

In [33]:
# Your answer here

y = np.arange(100, 0, -1).reshape(10, 10)

In [34]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
y

array([[100,  99,  98,  97,  96,  95,  94,  93,  92,  91],
       [ 90,  89,  88,  87,  86,  85,  84,  83,  82,  81],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 70,  69,  68,  67,  66,  65,  64,  63,  62,  61],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 50,  49,  48,  47,  46,  45,  44,  43,  42,  41],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31],
       [ 30,  29,  28,  27,  26,  25,  24,  23,  22,  21],
       [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11],
       [ 10,   9,   8,   7,   6,   5,   4,   3,   2,   1]])

In [35]:
grader.check("Question07")

Question07 results: All test cases passed!

8\. (0.6 pts) Select all the values that are in the first 3 rows and the last 7 columns of `x` and save the resulting array in `x_top_right`. Select all the values that are in the last 7 rows and the first 3 columns of `y` and save the resulting array in `y_bottom_left`.

In [36]:
# Your answer here 
x_top_right = x[:3, -7:]
y_bottom_left = y[-7:, :3]

In [37]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
x_top_right

array([[68, 68, 10, 84, 22, 37, 88],
       [13, 59, 66, 40, 88, 47, 89],
       [78, 73, 10, 21, 81, 70, 80]], dtype=int32)

In [38]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
y_bottom_left

array([[70, 69, 68],
       [60, 59, 58],
       [50, 49, 48],
       [40, 39, 38],
       [30, 29, 28],
       [20, 19, 18],
       [10,  9,  8]])

In [39]:
grader.check("Question08")

Question08 results: All test cases passed!

9\. (0.6 pts) Before we calculate the dot product of `x_top_right` and `y_bottom_left`, we want to confirm that the number of columns of `x_top_right` equals the number of rows of `y_bottom_left`. Compare the two values using the equality operator (==) and save the resulting True value in `ans9`. Do not directly put their values (i.e., 7) in the comparison.

In [40]:
# Your answer here 
ans9 = x_top_right.shape[1] == y_bottom_left.shape[0]

In [41]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
ans9

True

In [42]:
grader.check("Question09")

Question09 results: All test cases passed!

10\. (0.6 pts) Calculate the dot product of `x_top_right` and `y_bottom_left` and then save the resulting array in the variable `dot_prod`. 

In [43]:
# Your answer here 
dot_prod = np.dot(x_top_right, y_bottom_left)

In [44]:
# Check your answer here. (Do not make any change to this cell. Just run this cell.)
dot_prod

array([[14980, 14603, 14226],
       [13820, 13418, 13016],
       [15810, 15397, 14984]])

In [45]:
grader.check("Question10")

Question10 results: All test cases passed!

### Now that you have completed all the questions, click Kernel > Restart & Run All to creat a clean version of this notebook and check if all cells have run as expected. 